### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by dentemple** [mmhansen/pear#8]
Any thoughts so far on the open source license?

**Comment by mmhansen** [comment]
I'm not familiar with licensing. What is custom?

**Comment by dentemple** [comment]
By default, the creator of the repo retains full copyright over the code.  If this is what you want, that's fine.  But for many open source contributors, however, it may discourage participation in the project.  Open Source isn't truly open source without some sort of "openness", after all.  

Github provides a explanation for the most common licenses [here](http://choosealicense.com/).  For a project like this, I would recommend a strong copyleft license, like with the [GPLv3](http://choosealicense.com/licenses/gpl-3.0/).  On the other hand, for the true open source experience, there's a pure permissiveness approach like the [MIT License](http://choosealicense.com/licenses/mit/).

From a legal standpoint, it's far easier to move from stricter licensing to more permissive licensing, so we can always start with something like the GPL and then move to something like the MIT later on if people request it.

**Comment by mmhansen** [comment]
Okay, I'll get to reading some of that once I finish my finals. Thank you for the detailed explanation!
